### ISSUE TITLE
Message erreur photo

### ISSUE THREAD

**Issue by bflageul** [bflageul/BHS_CUBE_Deployment#1]
Vérifier les champs requis

> Un message d’erreur s’affiche quand on ne poste pas une photo dans une annonce (les champs devaient être tous requis)

**Comment by Eragonfr** [comment]
~~Correction temporaire… L'erreur ne s'affiche plus x)~~

**Comment by Eragonfr** [comment]
Closed by 8b86797a71e29c14cbaa132f5bea8d40497eea43
