### ISSUE TITLE
État de connexion après création d’un compte

### ISSUE THREAD

**Issue by bflageul** [bflageul/BHS_CUBE_Deployment#2]
Statut non connecté à la fin de la procédure de création d’un nouvel utilisateur.
Il serait judicieux de connecter l’utilisateur nouvellement inscrit.

> Quand un utilisateur s’enregistre il n’est pas connecté tout de suite après

**Comment by Eragonfr** [comment]
Fixed in [4c2c207](https://github.com/bflageul/BHS_CUBE_Deployment/commit/4c2c207d9ce0ef592b79457c6f42ef5d5522390b)
