### ISSUE TITLE
Fonction “se souvenir de moi” 

### ISSUE THREAD

**Issue by bflageul** [bflageul/BHS_CUBE_Deployment#3]
Vérifier le bon fonctionnement du bouton “se souvenir de moi” 

> J’ai l’impression que le bouton “se souvenir de moi” ne fonctionne pas, pouvez-vous vérifier ?

**Comment by Eragonfr** [comment]
La fonctionnalité n'est plus a jour vis a vis de l'utilisation actuelle d'internet (UX login de Google par exemple)
